//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Input/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""Burglar"",
            ""id"": ""8d37fe0c-e455-46fb-a4ca-ebd507d90159"",
            ""actions"": [
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""1ea505ae-90ef-4100-922a-9f7fca897ae4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""833c6ec4-6b0f-4752-bd79-dcfde4375a10"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Burglar
        m_Burglar = asset.FindActionMap("Burglar", throwIfNotFound: true);
        m_Burglar_Mouse = m_Burglar.FindAction("Mouse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Burglar
    private readonly InputActionMap m_Burglar;
    private IBurglarActions m_BurglarActionsCallbackInterface;
    private readonly InputAction m_Burglar_Mouse;
    public struct BurglarActions
    {
        private @Input m_Wrapper;
        public BurglarActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouse => m_Wrapper.m_Burglar_Mouse;
        public InputActionMap Get() { return m_Wrapper.m_Burglar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BurglarActions set) { return set.Get(); }
        public void SetCallbacks(IBurglarActions instance)
        {
            if (m_Wrapper.m_BurglarActionsCallbackInterface != null)
            {
                @Mouse.started -= m_Wrapper.m_BurglarActionsCallbackInterface.OnMouse;
                @Mouse.performed -= m_Wrapper.m_BurglarActionsCallbackInterface.OnMouse;
                @Mouse.canceled -= m_Wrapper.m_BurglarActionsCallbackInterface.OnMouse;
            }
            m_Wrapper.m_BurglarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mouse.started += instance.OnMouse;
                @Mouse.performed += instance.OnMouse;
                @Mouse.canceled += instance.OnMouse;
            }
        }
    }
    public BurglarActions @Burglar => new BurglarActions(this);
    public interface IBurglarActions
    {
        void OnMouse(InputAction.CallbackContext context);
    }
}
